### PR TITLE
Datadir Problems Patch

### PR DESCRIPTION
**Pull request by snowman2**

### CODE REVIEW

**Comment by snowman2** [comment]
Addresses: https://github.com/jswhit/pyproj/issues/176

**Comment by jswhit** [comment]
Should we get a 2.0.1 release out soon with this fix?

**Comment by snowman2** [comment]
@jswhit, yes I think getting this patch out sooner than later would be good. I just removed the change causing the build issues and targeted the exact fix. Should be good to merge when the build passes.

**Comment by snowman2** [comment]
It passes and is ready to merge.

**Pull request merged**
