### PR TITLE
updated to use sphinx to build docs

### LINKED ISSUE #161: upgrade docs to sphinx, create github.io page
Needs to be done for 2.0.0 release

### PR DESCRIPTION
**Pull request by snowman2**
Resolves #161

### CODE REVIEW

**Comment by snowman2** [comment]
https://snowman2.github.io/pyproj/

Missing the `_static` files for some reason.

**Comment by snowman2** [comment]
All works well now. I use the option to use the master with `docs/` folder to serve it up.
 You can see an example of how it will look at: https://snowman2.github.io/pyproj/.

**Comment by snowman2** [comment]
@jswhit, thoughts about replacing the installation section in the README with a link to the docs so it only needs to be updated in one place?

**Comment by jswhit** [comment]
Looks great!  Merging now. I will replace the installation instructions in the README with a link to the docs once I have it up on github.io.

**Comment by snowman2** [comment]
🎉 Sounds good to me.

**Pull request merged**
