### PR TITLE
support for unit conversion to/from radians for transform/itransform

### PR DESCRIPTION
**Pull request by snowman2**
For testing/discussion.

### CODE REVIEW

**Comment by snowman2** [comment]
```python
>>> from pyproj import *
>>> trans = transform(Proj(init="epsg:4214"), Proj(4326), 116.366, 39.867)
>>> trans
(116.366, 39.867)
>>> trans = transform(Proj(init="epsg:4214"), Proj(4326), 116.366, 39.867, out_radians=True)
>>> trans
(2.0309698373757215, 0.6958104128925793)
>>> pj = Proj(init="epsg:4214")
>>> transform(pj, Proj(4326), *pj(116.366, 39.867), in_radians=True)
(116.366, 39.867)
>>> transform(pj, Proj(4326), *pj(116.366, 39.867), in_radians=True, out_radians=True)
(2.0309698373757215, 0.6958104128925793)
```

**Comment by snowman2** [comment]
#185

**Comment by snowman2** [comment]
Only uses the `radians` flag now for backwards compatibility.

**Comment by jswhit** [comment]
Looks good to me.   It's probably better not to update the html docs in a separate pull request, since it makes it hard to sift through all the diffs.   Is there a test?

@andersonjacob, does this work for your use case?

**Comment by snowman2** [comment]
Sounds good. Removed the docs changes. The test is in the examples, but more tests never hurt :)

**Comment by jswhit** [comment]
OK - so we have coverage in the docstring tests.  Looks ready to merge, thanks @snowman2.  I'll wait a bit to see if @andersonjacob wants to weigh in.

**Comment by andersonjacob** [comment]
I took a quick look and it looks good to me.

**Comment by jswhit** [comment]
OK, merging now.

**Pull request merged**
