### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by ocefpaf**
Complementary to #32.  This is a very simple Travis config but should help assess new PRs.

### CODE REVIEW

**Comment by micahcochran** [comment]
:+1: Good idea.

**Comment by rsignell-usgs** [comment]
@jswhit , if this PR is merged before #32, we can see if indeed Travis picks up the problem, then hopefully merge #32 to fix it!

And if that all works, perhaps we could then get a new release so that continuum can build on windows (
https://github.com/ioos/conda-recipes/issues/534#issuecomment-157354393)?

**Comment by ocefpaf** [comment]
@rsignell-usgs This PR brings #32 with it.  I kind of wanted to see a green Travis-CI :wink: 

@jswhit Someone with write access needs to activated Travis-CI for the repository.

**Comment by jswhit** [comment]
travis is enabled, merging now...

**Pull request merged**
