### PR TITLE
Add version number string

### PR DESCRIPTION
**Pull request by micahcochran**
Add version number string variable for PROJ.4 and geodesic libraries.  Compatible for future versions of PROJ.4 after 4.10.0.  This comes on the heels of this PR https://github.com/OSGeo/proj.4/pull/364

Here's the console output of what this will add:
```Python
In [1]: import pyproj

In [2]: pyproj.proj_version_str
Out[2]: '4.9.2'

In [3]: pyproj.geodesic_version_str
Out[3]: '1.44.0'
```

This a versioning scheme that seems to follow [PEP 0440](https://www.python.org/dev/peps/pep-0440/).

### CODE REVIEW

**Comment by micahcochran** [comment]
Odd,  the [test passed in my repository](https://travis-ci.org/micahcochran/pyproj/builds/114288985).

**Comment by georgeouzou** [comment]
Nice, why is it odd @micahcochran ?

**Comment by micahcochran** [comment]
@georgeouzou  Github usually integrates Travis-CI testing result.  Most of the other pull requests for pyproj have a check mark ✔ upon all tests passing, and a or an X showing if a test failed.  Travis is a great tool in the toolkit of quality assurance, but it is occasionally buggy.

**Comment by georgeouzou** [comment]
Oh i got it,  this pull request has neither ✔ or X. Did you try to close and reopen the pull request?

**Comment by micahcochran** [comment]
Thanks @jswhit

**Pull request merged**
