### PR TITLE
Added class based version of Transformer

### PR DESCRIPTION
**Pull request by snowman2**
#187

### CODE REVIEW

**Comment by snowman2** [comment]
This is a start. Definitely needs documentation, tests, etc...

**Comment by snowman2** [comment]
This kind of refactor might be appropriate for a minor version increment instead of a patch. Thoughts on 2.1.0 for this change?

**Comment by jswhit** [comment]
Yes, I agree.  I'll go ahead and release 2.0.2 today.

**Comment by snowman2** [comment]
@jswhit if the tests pass & you are happy with the changes, it should be good to merge in.

**Comment by jswhit** [comment]
Looks great to me!  How about a version bump to 2.1.0 and an entry in history.rst?

After I merge this I'll do the repo move to pyproj4.

**Comment by snowman2** [comment]
Sounds good. I will do that this evening 👍

**Comment by snowman2** [comment]
Should I rebuild the docs as well?

**Comment by jswhit** [comment]
Sure

**Comment by snowman2** [comment]
Should be good to go now.

**Comment by jswhit** [comment]
Thanks @snowman2 - this is really nice.

**Comment by snowman2** [comment]
Glad you like it.

**Pull request merged**
