### PR TITLE
Add pyproj.itransform function

### PR DESCRIPTION
**Pull request by georgeouzou**
An added function "**itransform**" similar to pyproj.transform, that enables transformation using generators and iterators. I needed that functionality in a project of mine, i wanted to read a file line by line, transform and write back to file, so a generator function seemed nice.
I feel it is more natural to process multiple points as tuples of (x,y,z) instead of separate arrays of coordinates. 
I added a stride-version "**_transform_sequence**" function in _proj.pyx, using the underlying proj4.transform to accelerate itransform.

### CODE REVIEW

**Comment by georgeouzou** [comment]
Thanks, i will commit it right away!

**Comment by micahcochran** [comment]
For test/test_itransform.py, please use the print functions for Python 3 compatibility.

You could throw in the `from __future__ import print_function, with_statement`.  The `with` statement won't work in Python 2.4, but I assume there are less concerns with the tests.

**Comment by micahcochran** [comment]
I just submitted PR #55 that requests pyproj to stop supporting Python 2.4 and 2.5.  I thought this might be of interest to you.

**Comment by georgeouzou** [comment]
Very nice, this is indeed a welcome change! I will convert the code to support python 2.6+

**Comment by georgeouzou** [comment]
Just changed itransform function to drop support for python 2.4 & 2.5 as proposed on #55

**Comment by georgeouzou** [comment]
Should i close this request and build a fresh branch?

**Comment by micahcochran** [comment]
Github's merge can usually work with merging commits into your branch that have already been merged.  Sometime it GH doesn't know what to make of it.  Experienced user of git could probably take what you've done an squash it into one commit.   It is probably easier and cleaner if you just make a new PR on a fresh branch.

**Comment by georgeouzou** [comment]
Reopening this as an updated pull request

**Pull request closed without merging**
