### PR TITLE
fix error when data in Chinese folder

### PR DESCRIPTION
**Pull request by net21**

### CODE REVIEW

**Comment by micahcochran** [comment]
Issue #83 had some issues relating to utf-8, which I fixed in PR #88.

**Comment by net21** [comment]
@micahcochran set_datapath  will failed  using string type contains unicode characters in python 3.4 when real running.

**Comment by micahcochran** [comment]
1) Does the repository version have the bug?  2)  If YES, can you provide a little detail about how I can reproduce the bug on my end?

**Comment by micahcochran** [comment]
Test case data needed to reproduce the bug.

**Comment by micahcochran** [comment]
@net21 I'd like to close this bug.  Are there any reasons that I should not?

**Pull request closed without merging**
