### PR TITLE
Add Rackspace credentials

### PR DESCRIPTION
**Pull request by matthew-brett**
Usually there is also a clause at the end of .travis.yml, like:

after_success:
    # Upload wheels to Rackspace container
    - pip install wheelhouse-uploader
    - python -m wheelhouse_uploader upload --local-folder
          ${TRAVIS_BUILD_DIR}/wheelhouse/
          --no-update-index
          wheels

I guess you have to decide when you want to trigger this.

### CODE REVIEW

**Comment by jswhit** [comment]
Thanks @matthew-brett ! @snowman2 - any thoughts on how we will want to trigger the upload?

**Comment by snowman2** [comment]
Yeah, I can work on it in a PR later (maybe tonight) after merging. The plan is to modify the wheel script to build the wheel for the python version on a master non-PR build.

**Comment by snowman2** [comment]
Thoughts?

**Comment by jswhit** [comment]
We probably only want to trigger it for release tags.

**Pull request merged**
