### PR TITLE
use coverage reporting for coveralls.io

### PR DESCRIPTION
**Pull request by snowman2**
Not sure if this works or not. Would need to activate coveralls.io to test.

### CODE REVIEW

**Comment by snowman2** [comment]
Thoughts on activating coveralls for this repo?

**Comment by jswhit** [comment]
Not crucial for 2.0.0 release - I think a higher priority would be windows and macosx wheels.

**Comment by jswhit** [comment]
coveralls should be activated now

**Comment by snowman2** [comment]
Looks like it works: https://coveralls.io/github/jswhit/pyproj

**Pull request merged**
