### PR TITLE
Python3 Fixes.

### PR DESCRIPTION
**Pull request by citibeth**
Added a Python3 fix, in addition to what was fixed in PR #54.

This supercedes PR #54

### CODE REVIEW

**Comment by jswhit** [comment]
this pull request has conflicts with master that need to be resolved before it can be merged

**Comment by citibeth** [comment]
OK, resolved.  The conflicts were spurious, in the sense that they were in a Cython-generated file, not a source file.  I set everything to be consistent with the corresponding .pyx file.

**Comment by georgeouzou** [comment]
I have just included the fix in a fresh #72, that continues on the changes that @micahcochran did.

**Comment by citibeth** [comment]
Superseded by #73.

**Pull request closed without merging**
