### PR TITLE
Change Proj.to_latlong in order to return an instance of pyproj.Proj

### PR DESCRIPTION
**Pull request by georgeouzou**
Returning a **pyproj.Proj** instance instead of the underlying base class **_proj.Proj** in **pyproj.Proj.to_latlong** function feels more intuitive.   
This patch adresses a bug as well in pyproj.transform's function check. See [Issue #53 ](https://github.com/jswhit/pyproj/issues/53)

### CODE REVIEW

**Comment by citibeth** [comment]
Can this PR be merged?  I still need this to work.

**Comment by jswhit** [comment]
please resolve the conflicts with master, and then I'll merge

**Comment by georgeouzou** [comment]
Reopened this as an updated pull request #72

**Comment by jswhit** [comment]
test is failing, since _proj_version_str apparently no longer exists.

**Comment by georgeouzou** [comment]
I will update pull request #72 to resolve the conflicts.

**Pull request closed without merging**
