### PR TITLE
add filter for boolean values in dict2string so "no_rot=True" works  (issue #183)

### PR DESCRIPTION
**Pull request by jswhit**

### CODE REVIEW

**Comment by snowman2** [comment]
Also, what about if they use None for the value?

**Comment by jswhit** [comment]
handles False and None now

**Comment by snowman2** [comment]
I was thinking `None` could be considered analagous to True as the `None` would be considered the same as not having a value for the argument. Thoughts on this logic?

```python
...
if value is None or (type(value) is bool and value):
    pjargs.append("+" + key + " ")
elif type(value) is bool and not value:
    pass
...
```

**Comment by snowman2** [comment]
Just updated the code ^^

**Comment by jswhit** [comment]
Or None might be interpreted as don't have a no_rot flag added to the string....

**Comment by snowman2** [comment]
It seems cartopy interprets None as not having a value.
See: https://github.com/SciTools/cartopy/blob/45d0479abed27f73c5bb8bac35036772a3faa773/lib/cartopy/_crs.pyx#L177

**Comment by jswhit** [comment]
OK, changed it to your suggestion

**Comment by snowman2** [comment]
Sounds good, thanks for fixing this 👍

**Comment by TAlonglong** [comment]
Thank you for this quick respond to my issue.

**Pull request merged**
