### PR TITLE
Use setuptools when available.

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR makes use of setuptools, when available, allowing for easy Windows builds via
[Microsoft Visual C++ Compiler for Python 2.7](http://www.microsoft.com/en-us/download/details.aspx?id=44266) as requested by @rsignell-usgs.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I verified that this works.  Super cool.   Finally, a lightweight way to build python binaries on windows, and from Microsoft!    Setuptools >6.0 can figure out where the compiler is, but distutils cannot.

**Comment by rsignell-usgs** [comment]
@jswhit  poke?

**Comment by ocefpaf** [comment]
@jswhit Let me know if you want me to close this or re-write in a clearer way.

**Comment by ocefpaf** [comment]
Closing this...

**Pull request closed without merging**
