### PR TITLE
Use Cython in setup.py to generate C code on the fly from _proj.pyx.

### PR DESCRIPTION
**Pull request by micahcochran**
This is a proposed policy change to remove _proj.c from the repository and only have it in the release versions.   This will remove the exchange of different versions of _proj.c using generated using the different versions of Cython.  I intend this to improve the project maintainability.

For repository downloads, setup.py will use Cython to generate _proj.c for compilation.

Most of the current (2016-04-16) Pull Requests in one way or another edit or make changes to _proj.pyx (and _proj.c), so merging this first could cause problems for merging the other PRs.  Seeing as most every one of them has conflicts.  It might not be such a bad thing.

I made an extra file "requirements-dev.txt", a [pip requirements file](https://pip.readthedocs.org/en/1.1/requirements.html), that contains all the names of the needed modules for installation for development and testing on Travis and Appveyor.  I changed the testing services to use that file for dependency installation.

**EDIT:** [Appveyor passed too](https://ci.appveyor.com/project/micahcochran/pyproj/build/1.0.18).

### CODE REVIEW

**Comment by georgeouzou** [comment]
Very nice proposal!

**Comment by jdkloe** [comment]
I am also happy with this change.

**Comment by jswhit** [comment]
this adds cython as a dependency, which I don't like.  Perhaps setup.py could try importing cython, and if it succeeds, use it  - otherwise use the repo version of _proj.c.

**Comment by citibeth** [comment]
+1

**Comment by micahcochran** [comment]
@citibeth I agree fully about treating Cython similar to how many projects treat autotools.  Well put.

[Fiona ](https://github.com/Toblerity/Fiona) has 6 .pyx files.  That project requires Cython when building from the repository.

If I make a small change to the .pyx file, and I use a different Cython version I get 1,000 lines of changes that git won't be able to merge.

Installing Cython depends upon a C compiler to be installed.  pyproj requires a compiler to build _proj.c.  Therefore if you can install pyproj (using pip, easy_install, or running python setup.py), you should be able to install Cython without too much trouble.

> Perhaps setup.py could try importing cython, and if it succeeds, use it - otherwise use the repo version of _proj.c.

There will need to be another Travis test that the _proj.pyx and the _proj.c  versions test the same.  I think that only causes more confusion and problems. I can see someone (namely myself) testing it on their machine, it ran just fine, and forgetting to regenerate the _proj.c file.  If this PR is just going to make submitting to the the project more complicated, I'll just close the PR and forget about it.

**Comment by georgeouzou** [comment]
As in Fiona or Shapely **setup.py**, when building from the repo, it could require Cython in contrast to getting it as an source distribution.

**Comment by micahcochran** [comment]
> I could thus be only a dev-requirement.
That is exactly I'm proposing with this PR.

**Comment by jswhit** [comment]
OK, you convince me.  Merging now...

**Comment by jswhit** [comment]
@micahcochran  - I've added you as a 'collaborator' to the pyproj project, so you can go ahead and merge this once the tests have passed.

**Comment by micahcochran** [comment]
Thanks @jswhit . We'll discuss further later.

**Pull request merged**
